spring:
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:petclinic;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Change to 'validate' in production
    hibernate:
      ddl-auto: update
    show-sql: false

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
